[ElasticSearch]
    Username = "basic_auth_username"
    Password = "basic_auth_password"
[Prometheus]
    PrometheusBaseURL = "https://join-testnet.elrond.com"
    JoinRoute = "/join"
    StatusRoute = "/status"
