[ESDTSystemSCConfig]
    BaseIssuingCost = "5000000000000000000" #5ERD
    OwnerAddress = "erd1932eft30w753xyvme8d49qejgkjc09n5e49w4mwdjtm0neld797su0dlxp"

[GovernanceSystemSCConfig]
	ProposalCost = "5000000000000000000" #5ERD
	NumNodes     = 500
	MinQuorum    = 400
	MinPassThreshold = 300
	MinVetoThreshold = 50
